### ISSUE TITLE
lockup if using a RAM based mapper

### ISSUE THREAD

**Issue by zmajcenic** [turbor/msxblockpuzzle#1]
Hi,
as mentioned in the thread
https://msx.org/news/challenges/en/msxdev20-blockpuzzle
the game has a bug in one of the initialization routines
file: intro.asc
function: initintronameblock 
because at some point it attempts to write below #C000 which is in the ROM area of the game.
However when the game is launched via memory mapper that uses RAM the game corrupts itself.

I solved it by adding following code at the beginning of initintronameblock:
	ld a, d
	cp #c0
	ret c

My claims of self corruption can be seen if you add following watchpoint inside openMSX console
debug set_watchpoint write_mem {0x4000 0xbfff}

**Comment by turbor** [comment]
Thanks for the bug report.
It turned out a missing INC HL was the culprit. 
I was iterating over a list of 16bits address  but the missing INC caused the code to read twice the amount of pointers. Every odd pointer was thus invalid and caused the rest of the program to write below the #C000 address.
